
ALTER TABLE dbo.SanPhamGiay NOCHECK CONSTRAINT FK__SanPhamGia__MaLG__1BFD2C07;
ALTER TABLE dbo.SanPhamGiay NOCHECK CONSTRAINT FK__SanPhamGi__MaNCC__1CF15040;
ALTER TABLE dbo.SizeGiay NOCHECK CONSTRAINT FK__SizeGiay__MaSPG__22AA2996;
DELETE FROM dbo.SanPhamGiay;
DELETE FROM dbo.SizeGiay;
ALTER TABLE dbo.SanPhamGiay CHECK CONSTRAINT FK__SanPhamGia__MaLG__1BFD2C07;
ALTER TABLE dbo.SanPhamGiay CHECK CONSTRAINT FK__SanPhamGi__MaNCC__1CF15040;
ALTER TABLE dbo.SizeGiay CHECK CONSTRAINT FK__SizeGiay__MaSPG__22AA2996;
EXEC sp_MSforeachtable 'DELETE FROM ?'